### PR TITLE
Frontend show car

### PR DESCRIPTION
**Pull request by kristianeaw**

### CODE REVIEW

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Shamzaa** [comment]
When I press accept after finding my car, the backend throws an error.
http://prntscr.com/jf6mnw 
under save:

**Comment by Shamzaa** [comment]
fixed car object sent to backend, and feedback in frontend when you accept your current car.

TODO: dispatch current user, so the  state.auth.car is updated.

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Shamzaa** [comment]
When I register a car with a user, then make a new account:
* I am greeted with the front page asking me to register my car
* when I click it I see details about the car I registered for the previous user

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-frontend-show-car

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Pull request merged**
