### PR TITLE
Backend api sample m2

### PR DESCRIPTION
**Pull request by Shamzaa**

### CODE REVIEW

**Comment by Chr1stian** [comment]
Do we want to create tests for this before merging?

**Comment by Shamzaa** [comment]
as this is just a feature to implement the basics of communicating with the API, I don't see the need of having tests written for it, as the code will be just used as reference for further code.

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-Backend-api-sample-m2

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Chr1stian** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@preference/BilparkApp-Backend-api-sample-m2

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Pull request merged**
